language: csharp
mono: none
dotnet: 2.2.402
# safelist
branches:
  only:
  - master
install:
- dotnet restore
script:
- dotnet build
- dotnet test Tests/Plugins.Events.Tests/Plugins.Events.Tests.csproj
